-include .env

.PHONY: all test clean deploy fund help install snapshot format anvil 

DEFAULT_ANVIL_KEY := 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

help:
	@echo "Usage:"
	@echo "  make deploy [ARGS=...]\n    example: make deploy ARGS=\"--network sepolia\""
	@echo ""
	@echo "  make fund [ARGS=...]\n    example: make deploy ARGS=\"--network sepolia\""

all: clean remove install update build

# Clean the repo
clean  :; forge clean

# Remove modules
remove :; rm -rf .gitmodules && rm -rf .git/modules/* && rm -rf lib && touch .gitmodules && git add . && git commit -m "modules"

install :; forge install Cyfrin/foundry-devops@0.0.11 --no-commit && forge install foundry-rs/forge-std@v1.5.3 --no-commit && forge install openzeppelin/openzeppelin-contracts@v4.8.3 --no-commit

# Update Dependencies
update:; forge update

build:; forge build

test :; forge test 

snapshot :; forge snapshot

format :; forge fmt

anvil :; anvil -m 'test test test test test test test test test test test junk' --steps-tracing --block-time 1

NETWORK_ARGS := --rpc-url http://localhost:8545 --private-key $(DEFAULT_ANVIL_KEY) --broadcast

ifeq ($(findstring --network sepolia,$(ARGS)),--network sepolia)
	NETWORK_ARGS := --rpc-url $(https://eth-sepolia.g.alchemy.com/v2/ARdICeNeCzo5ImYFmq5Ai64R4JLd9-k7) --private-key $(bfeeed858983348c846519cf4b5f055a9aab02408931346984e7286795767524) --broadcast --verify --etherscan-api-key $(AXKW6AN4NAUBZ42AFQIQY6MW25VCKUKEYT) -vvvv
endif

deploy:
	@forge script script/DeployBasicNft.s.sol:DeployBasicNft $(NETWORK_ARGS)

deployMood:
	@forge script script/DeployMoodNft.s.sol:DeployMoodNft $(NETWORK_ARGS)

mintMoodNft:
	@forge script script/Interactions.s.sol:MintMoodNft $(NETWORK_ARGS)

	mint:
	@forge script script/Interactions.s.sol:mintNft $(NETWORK_ARGS)


flipMoodNft:
	@forge script script/Interactions.s.sol:FlipMoodNft $(NETWORK_ARGS)

	--rpc-url https://eth-sepolia.g.alchemy.com/v2/ARdICeNeCzo5ImYFmq5Ai64R4JLd9-k7 --private-key bfeeed858983348c846519cf4b5f055a9aab02408931346984e7286795767524 --broadcast --verify --etherscan-api-key AXKW6AN4NAUBZ42AFQIQY6MW25VCKUKEYT -vvvv

	 forge script script/interaction.s.script.sol:MintBasicNft --rpc-url https://eth-sepolia.g.alchemy.com/v2/ARdICeNeCzo5ImYFmq5Ai64R4JLd9-k7 --private-key bfeeed858983348c846519cf4b5f055a9aab02408931346984e7286795767524 --broadcast --verify --etherscan-api-key AXKW6AN4NAUBZ42AFQIQY6MW25VCKUKEYT -vvvv
	forge script script/Interactions.s.sol:MintBasicNft
cast send --rpc-url https://eth-sepolia.g.alchemy.com/v2/ARdICeNeCzo5ImYFmq5Ai64R4JLd9-k7 0xca9378B2Fa5E934d90eB5eCe93AbaF3F7D13e662  "mintTo(0x251EC159AD1dfA90C82e08b6Ae9aB195B375AEEA)" --private-key=bfeeed858983348c846519cf4b5f055a9aab02408931346984e7286795767524
	
forge script script/interaction.s.script.sol:MintBasicNft --rpc-url https://eth-sepolia.g.alchemy.com/v2/ARdICeNeCzo5ImYFmq5Ai64R4JLd9-k7 --private-key bfeeed858983348c846519cf4b5f055a9aab02408931346984e7286795767524 --broadcast --verify --etherscan-api-key AXKW6AN4NAUBZ42AFQIQY6MW25VCKUKEYT -vvvv